[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyACM3
monitor_port = /dev/ttyACM3
upload_protocol = custom
upload_command = bash scripts/flash.sh
board_build.filesystem = spiffs
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    olikraus/U8g2 @ ^2.35.9
    chris--a/Keypad @ ^3.1.1
    https://github.com/DECE2183/libLua.git